name: SimpleBan
version: 1.0.0
main: de.wrn.simpleban.SimpleBan
api-version: 1.21
author: WRN
description: A simple and expandable Minecraft ban system.

commands:

  permban:
    description: Permanently bans a player.
    usage: /permban <player> <reason>
    permission: simpleban.permban

  tempban:
    description: Temporarily bans a player.
    usage: /tempban <player> <time> <reason>
    permission: simpleban.tempban


permissions:

  simpleban.permban:
    description: Allows permanent bans.
    default: op

  simpleban.tempban:
    description: Allows temporary bans.
    default: op
